#!/bin/sh
CHERRYUSER=cherrypop
IF=br-eth0
MYIP=`ip addr show $IF|grep "inet "|cut -d" " -f6|cut -d"/" -f1`
BROADCAST=`ip addr show $IF|grep "inet "|cut -d" " -f8`
if [ "$1" = "" ]; then
	echo "Usage: cherrypop [start|stop|restart]"
	exit
fi

if [ "$1" = "start" ]; then
	echo starting cherrypop
	sudo -u cherrypop /usr/sbin/discoveryd $MYIP $BROADCAST:2500 >/dev/null 2>/dev/null && sudo -u cherrypop /usr/sbin/vmrunnerd $MYIP >/dev/null 2>/dev/null && sudo -u cherrypop /usr/sbin/runner.sh $MYIP >/dev/null 2>/dev/null
fi
if [ "$1" = "stop" ]; then
	echo stopping cherrypop
	killall discoveryd
	killall vmrunnerd
	killall -w runner.sh
fi
if [ "$1" = "restart" ]; then
	$0 stop
	$0 start
fi

